
services:
  client:
    container_name: client
    build:
      context: ./
      dockerfile: dockerfile
    restart: always
    ports:
      - '80:80'
    networks:
      - api_network

networks:
  api_network:
    external: true

volumes:
  portainer_data: