version: "3"

services:
  client:
    container_name: client
    build:
      context: ./
      dockerfile: dockerfile.api
    volumes:
      - client_data:/app/
    ports:
      - '80:80'

volumes:
  client_data: